## **Worksheet - 0**

In [44]:
import numpy as np

### **1. Basic Vector and Matrix Operation with Numpy**

### Problem - 1: Array Creation:

In [45]:
# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

Empty Array:
 [[4.9e-324 1.5e-323]
 [1.5e-323 4.9e-324]]


In [39]:
# 2. Initialize an all-one array with size 4X2
ones_array = np.ones((4, 2))
print("All Ones Array:\n", ones_array)

All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [40]:
# 3. Return a new array of given shape and type, filled with fill value
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print("Filled Array:\n", filled_array)

Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [41]:
# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("Zeros Like Array:\n", zeros_like_array)

Zeros Like Array:
 [[0 0 0]
 [0 0 0]]


In [42]:
# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("Ones Like Array:\n", ones_like_array)

Ones Like Array:
 [[1 1 1]
 [1 1 1]]


In [43]:
# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted NumPy Array:\n", numpy_array)

Converted NumPy Array:
 [1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [46]:
# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [47]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\Random Array Mean:", mean_value)

\Random Array Mean: 0.5005394963855504


In [50]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("Min value:", min_value, "Max value:", max_value)

Min value: 0.004998289831889768 Max value: 0.9987129218787908


In [51]:
# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero Array with 5th element as 1:\n", zero_array)

Zero Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [52]:
# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

Reversed Array:
 [0 4 0 0 2 1]


In [53]:
# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 on border and 0 inside:\n", border_array)

2D Array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
# 9. Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations:

In [55]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [56]:
# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

Addition of x and y:
 [[ 6  8]
 [10 13]]


In [57]:
# 2. Subtract the two arrays
sub_xy = x - y
print("Subtraction of x and y:\n", sub_xy)

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [58]:
# 3. Multiply the array with an integer (e.g., 3)
mult_x = x * 3
print("Multiplication of x with 3:\n", mult_x)

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]


In [59]:
# 4. Find the square of each element of the array
square_x = np.square(x)
print("Square of each element in x:\n", square_x)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [60]:
# 5. Find the dot product
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y

print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [61]:
# 6. Concatenate x and y along rows
concat_xy_row = np.concatenate((x, y), axis=0)
print("Concatenation of x and y along rows:\n", concat_xy_row)

# Concatenate v and w along columns
concat_vw_col = np.vstack((v, w))  # Using vstack (same as np.concatenate with axis=0)
print("Concatenation of v and w along columns:\n", concat_vw_col)

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]


In [63]:
# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("Error while concatenating x and v:", e)

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


The error happens because x is a 2x2 matrix, while v is a 1D array. To fix it, reshape v into a column vector using v.reshape(-1, 1).

### Problem - 4: Matrix Operations:

In [66]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
# 1. Prove A * A^(-1)= I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^(-1) = I:\n", np.round(identity_matrix, decimals=5))

# 2. Prove AB ̸= BA.
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.array_equal(AB, BA))  # This should return False

# 3. Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T:\n", AB_T)
print("B^T A^T:\n", BT_AT)
print("(AB)^T == B^T A^T?", np.array_equal(AB_T, BT_AT))  # This should return True

A * A^(-1) = I:
 [[1. 0.]
 [0. 1.]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA? False

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T A^T? True


In [67]:
# Solving the system of linear equations:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Representing as AX = B
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficients matrix
B_matrix = np.array([-1, -3, 9])  # Constant matrix

# Solving using inverse method: X = A⁻¹ * B
A_inv = np.linalg.inv(A_matrix)  # Compute inverse of A
X = np.dot(A_inv, B_matrix)  # Solution for X
print("\nSolution using Inverse Method:\n", X)

# Alternative approach: Using np.linalg.solve()
X_solve = np.linalg.solve(A_matrix, B_matrix)
print("\nSolution using np.linalg.solve():\n", X_solve)


Solution using Inverse Method:
 [ 2.  1. -2.]

Solution using np.linalg.solve():
 [ 2.  1. -2.]


### **2. Experiment: How Fast is Numpy?**

In [68]:
import time

In [69]:
# 1. Element-wise Addition

# Using Python lists
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000, 2_000_000)]
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(1_000_000)]  # Element-wise addition
end_time = time.time()
print(f"Element-wise addition using Python lists took: {end_time - start_time:.6f} seconds")

# Using NumPy arrays
np_array1 = np.arange(1_000_000)
np_array2 = np.arange(1_000_000, 2_000_000)
start_time = time.time()
result_np = np_array1 + np_array2  # Element-wise addition
end_time = time.time()
print(f"Element-wise addition using NumPy arrays took: {end_time - start_time:.6f} seconds")

Element-wise addition using Python lists took: 0.142377 seconds
Element-wise addition using NumPy arrays took: 0.007966 seconds


In [70]:
# 2. Element-wise Multiplication

# Using Python lists
start_time = time.time()
result_list_mult = [list1[i] * list2[i] for i in range(1_000_000)]  # Element-wise multiplication
end_time = time.time()
print(f"Element-wise multiplication using Python lists took: {end_time - start_time:.6f} seconds")

# Using NumPy arrays
start_time = time.time()
result_np_mult = np_array1 * np_array2  # Element-wise multiplication
end_time = time.time()
print(f"Element-wise multiplication using NumPy arrays took: {end_time - start_time:.6f} seconds")

Element-wise multiplication using Python lists took: 0.185417 seconds
Element-wise multiplication using NumPy arrays took: 0.008147 seconds


In [71]:
# 3. Dot Product

# Using Python lists
start_time = time.time()
dot_product_list = sum([list1[i] * list2[i] for i in range(1_000_000)])  # Dot product
end_time = time.time()
print(f"Dot product using Python lists took: {end_time - start_time:.6f} seconds")

# Using NumPy arrays
start_time = time.time()
dot_product_np = np.dot(np_array1, np_array2)  # Dot product
end_time = time.time()
print(f"Dot product using NumPy arrays took: {end_time - start_time:.6f} seconds")

Dot product using Python lists took: 0.256972 seconds
Dot product using NumPy arrays took: 0.002123 seconds


In [73]:
# 4. Matrix Multiplication

# Using Python lists (1000x1000 matrices)
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]
start_time = time.time()
result_matrix_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]  # Matrix multiplication
end_time = time.time()
print(f"Matrix multiplication using Python lists took: {end_time - start_time:.6f} seconds")

# Using NumPy arrays (1000x1000 matrices)
np_matrix1 = np.random.rand(1000, 1000)
np_matrix2 = np.random.rand(1000, 1000)
start_time = time.time()
result_matrix_np = np.dot(np_matrix1, np_matrix2)  # Matrix multiplication
end_time = time.time()
print(f"Matrix multiplication using NumPy arrays took: {end_time - start_time:.6f} seconds")

Matrix multiplication using Python lists took: 185.876719 seconds
Matrix multiplication using NumPy arrays took: 0.111267 seconds
